Disable some static_assert()'s which cause a compilation failure on windows arm with VS 2019:
```
D:\a\1\s\llvm\include\llvm/ADT/SmallVector.h(524): error C2719: 'Elt': formal parameter with requested alignment of 16 won't be aligned
  D:\a\1\s\llvm\include\llvm/ADT/SmallVector.h(554): note: see reference to class template instantiation 'llvm::SmallVectorTemplateBase<T,true>' being compiled
          with
          [
              T=`anonymous-namespace'::Struct16B
          ]
```